<a href="https://colab.research.google.com/github/err0r6447-dev/python_lib_tutorials/blob/main/Numpy/begineer/section1_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧩 Section 1 — The NumPy Mindset: Arrays as the Foundation of Numerical Python

## 🧠 Why NumPy Arrays Matter

NumPy’s core innovation is the **n-dimensional array**, or `ndarray`.  
Unlike Python lists, which are flexible but slow and memory-hungry, NumPy arrays store **homogeneous data** (all elements of one type) in **contiguous memory blocks**.  
This makes element-wise arithmetic and matrix operations incredibly fast — NumPy calls into **optimized C and Fortran routines** behind the scenes.  

You can think of NumPy as the “engine room” of the scientific Python ecosystem — powering pandas, scikit-learn, TensorFlow, and more.

In this section, we’ll:
- Build and inspect arrays.
- Learn about shapes, dtypes, and memory.
- Contrast arrays with lists.
- Understand why NumPy is the *lingua franca* of numerical Python.

In [3]:
import numpy as np

# Check version (important for reproducibility)
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## 🧱 Creating Your First Arrays

Let's start by constructing arrays from Python lists.  
An array is essentially a **grid of values**, all of the same type, indexed by a tuple of non-negative integers.  

NumPy automatically infers the data type (`dtype`) from the input — but you can specify one explicitly if needed.

In [4]:
# 1D array from a Python list
a = np.array([2, 4, 6, 8])
print("Array a:", a)
print("Type:", type(a))
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Data type:", a.dtype)

Array a: [2 4 6 8]
Type: <class 'numpy.ndarray'>
Shape: (4,)
Dimensions: 1
Data type: int64


In [5]:
# 2D array (matrix)
b = np.array([[1.5, 2.0, 2.5],
              [3.0, 3.5, 4.0]])
print("Array b:\n", b)
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)

Array b:
 [[1.5 2.  2.5]
 [3.  3.5 4. ]]
Shape: (2, 3)
Dimensions: 2
Data type: float64


Notice that:
- Each row must have the same length (NumPy enforces rectangular structure).
- The array has both **shape** and **number of dimensions (ndim)**.
- The dtype is inferred (`float64` here).

Arrays can be of any numeric type — integers, floats, complex numbers — or even booleans.

In [6]:
# Example: integer, float, and boolean arrays
ints = np.array([1, 2, 3], dtype=np.int32)
floats = np.array([1.1, 2.2, 3.3])
bools = np.array([True, False, True])

print("ints:", ints, "| dtype:", ints.dtype)
print("floats:", floats, "| dtype:", floats.dtype)
print("bools:", bools, "| dtype:", bools.dtype)

ints: [1 2 3] | dtype: int32
floats: [1.1 2.2 3.3] | dtype: float64
bools: [ True False  True] | dtype: bool


## 🧩 Array Initialization Patterns

NumPy provides a variety of efficient ways to create arrays without typing out lists.  
These *array constructors* are especially useful in data science and simulations where you often need grids or zero-filled placeholders.

In [7]:
# Common initialization shortcuts
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
arange_ex = np.arange(0, 10, 2)      # like range(), but returns an array
linspace_ex = np.linspace(0, 1, 5)   # evenly spaced numbers between 0 and 1

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:\n", arange_ex)
print("Linspace:\n", linspace_ex)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Arange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


### 🧮 Why These Matter

Functions like `np.arange()` and `np.linspace()` are the backbone of numerical modeling and plotting —  
for instance, generating time steps, coordinates, or sample points in simulations.

Another powerful option: create uninitialized arrays for maximum performance.

In [8]:
# Fast but risky: creates an array with arbitrary (uninitialized) memory values
empty_array = np.empty((2, 3))
print(empty_array)

[[1. 1. 1.]
 [1. 1. 1.]]


⚠️ `np.empty()` does **not** zero out memory — it just allocates it.  
Always overwrite it before using the data, or you’ll get unpredictable results.

## ⚙️ Array Attributes and Basic Properties

Once you have an array, you can inspect its properties to understand its internal layout and memory footprint.

This helps you debug shape or dtype mismatches quickly — a common source of errors for beginners.

In [9]:
data = np.random.randint(0, 100, size=(3, 4))  # a random 3x4 array
print("Data:\n", data)
print("Shape:", data.shape)
print("Size (# elements):", data.size)
print("Item size (bytes per element):", data.itemsize)
print("Total bytes (size * itemsize):", data.nbytes)

Data:
 [[47 12 65 15]
 [64 98 69 43]
 [43 82 41 33]]
Shape: (3, 4)
Size (# elements): 12
Item size (bytes per element): 8
Total bytes (size * itemsize): 96


Every NumPy array tracks:
- `shape`: dimensions (rows, columns, etc.)
- `size`: total number of elements
- `itemsize`: bytes used per element
- `nbytes`: total memory footprint

This memory control is a big reason NumPy is fast and predictable — it knows exactly how data is laid out in RAM.

## 🔍 Under the Hood: Why NumPy Is Fast

NumPy’s magic lies in **C-contiguous memory** and **vectorized C loops**.

When you do `a + 1`, NumPy doesn’t loop in Python — it calls highly optimized C code that operates on the entire block of memory in parallel.  
This is called **vectorization** — and it’s what makes NumPy 10–100× faster than lists for large computations.

Each array internally stores:
1. A pointer to a contiguous memory buffer.
2. The `dtype` descriptor (how to interpret bytes).
3. The array’s `shape` (rows × columns).
4. The `strides` (byte steps between elements in each dimension).

You can inspect strides directly:

In [10]:
print("Array strides (in bytes):", data.strides)

Array strides (in bytes): (32, 8)


The stride values tell you how many bytes NumPy jumps in memory when moving along each axis.  
Understanding strides becomes essential later when working with **views**, **transposes**, and **broadcasting**.

## ⚠️ Best Practices / Pitfalls

✅ Use NumPy arrays for *all numeric* operations — Python lists are slow and lack shape information.  
✅ Keep arrays **homogeneous**: one consistent data type per array.  
✅ Use `dtype` explicitly when performance or precision matters (e.g., `float32` for ML, `int64` for counts).  
✅ Prefer built-in constructors (`zeros`, `ones`, `arange`, etc.) over list conversions for clarity and speed.  

⚠️ Beware:
- Mixing data types (like ints and strings) upcasts the array to `object`, disabling fast math.
- Using `np.array()` always copies data; use `np.asarray()` if you want a **view** (no copy).
- Never rely on uninitialized `np.empty()` data without overwriting it first.

## 🧩 Challenge Exercise — "Daily Sales Snapshot"

**Scenario:**  
You manage a small shop with three products (A, B, C).  
You recorded their sales (in units) over three days:

| Day | Product A | Product B | Product C |
|-----|------------|------------|------------|
| 1   | 10         | 15         | 12         |
| 2   | 8          | 19         | 11         |
| 3   | 14         | 22         | 9          |

**Tasks:**
1. Create a 3×3 NumPy array for this data.  
2. Print its `shape`, `size`, and `dtype`.  
3. Compute total sales (sum of all elements).  
4. Compute average sales per product (column-wise mean).  
5. What happens if you accidentally mix integers and strings in the array?

*(Try it before moving to the next section!)*

✅ **Next Up:**  
In **Section 2**, we’ll explore **array shapes, indexing, and axes** — how to navigate and reshape multidimensional data efficiently.

# --- End of Section 1 — Continue to Section 2 ---